In [24]:
import pandas as pd
import random

In [27]:
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  robot
2  robot
3  human
4  human

###### Ваша задача перевести его в one hot вид без get_dummies?

In [26]:
data.loc[data['whoAmI'] == 'human', 'whoAmI_hum'] = 1
data.loc[data['whoAmI'] != 'human', 'whoAmI_hum'] = 0
data.loc[data['whoAmI'] != 'human', 'whoAmI_robot'] = 1
data.loc[data['whoAmI'] == 'human', 'whoAmI_robot'] = 0
data.whoAmI_hum = data.whoAmI_hum.astype(int)
data.whoAmI_robot = data.whoAmI_robot.astype(int)
data.head()

  whoAmI  whoAmI_hum  whoAmI_robot
0  robot           0             1
1  human           1             0
2  robot           0             1
3  human           1             0
4  robot           0             1